### ISSUE TITLE
Reviewing Firefox Extensions - When was it installed? Interpreting extensions.json

### ISSUE THREAD

**Issue by brisdaz** [jscher2000/Firefox-File-Utilities#1]
From [Reviewing Firefox Extensions - When was it installed? - Super User](https://superuser.com/questions/1512094/reviewing-firefox-extensions-when-was-it-installed):

I wish for a similar web app to Scrounger to interpret extensions.json displaying a sortable list/table of extension name, AMO extension link and install date.

**Comment by jscher2000** [comment]
Hi brisdaz, I'm sure that's possible. Maybe I can do it as an enhancement of my extension lookup page, adding the local information from the extensions.json file somewhere:

https://www.jeffersonscher.com/sumo/extensionlist.html

**Comment by jscher2000** [comment]
Or: https://www.jeffersonscher.com/ffu/extensionsjson.html

**Comment by brisdaz** [comment]
Hi jscher2000, 

Thanks for the quick response!

Would it be possible to separate the date columns into install date and updated date? That way I could use [TableTools2](https://www.mingyi.org/TableTools2/index.html) to easily sort the html table.

Also I note that despite my operating system and browser set to Australian date format you've used US date format. Perhaps as a compromise you can use [ISO date format](https://en.wikipedia.org/wiki/ISO_8601) or use javascript to find the locale to show the correct format?

Merry Xmas! 

Do you have a donation or tip jar or preferred charity? I can't donate much but say a coffee at $5AUD be fine? Your Firefox Scrounger has been helpful and so is this.

**Comment by jscher2000** [comment]
Hi, I've split the dates into two columns. 

The date is formatted using [toLocaleString()](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString) which should follow your browser's expressed locale (or language) preference. Anyway, rather than try to figure out why it doesn't work on yours, I added format options to override it.

No need to donate to me, but you could always donate to Mozilla. https://donate.mozilla.org/

**Comment by brisdaz** [comment]
Thanks - I thought I  installed the British edition of Firefox and thus had the correct Locale set. Unfortunately I found out it was set to en-US which I corrected. Shouldn't there be a check for the OS locale when Firefox loads?

Also with donation to Mozilla I will do so soon, after this is maybe answered - [Donation - Lowest transaction fee for an Australian - Google Groups](https://groups.google.com/forum/#!topic/mozilla.general/gl--Bb77BGw)

**Comment by jscher2000** [comment]
> Shouldn't there be a check for the OS locale when Firefox loads?

The locale is baked in during the build process. If you use the small stub installer, it will try to select the most appropriate locale build. If you download a full installer, then you can pick any locale you like (or don't like, as the case may be).

**Comment by brisdaz** [comment]
# Sortable table

This seems easy to drop into your code:

* [sorttable: Make all your tables sortable](https://kryogenix.org/code/browser/sorttable/)
> 1. Download the Javascript library
> 2. Include the Javascript library, by putting a link to it in the HEAD of your page, like so:
>    `<script src="sorttable.js"></script>`
>  3. Mark your table as a sortable one by giving it a class of "sortable":
>   `<table class="sortable">`
>
>    Note that the library's JavaScript file is called sorttable (two Ts), but the class you add to the table is sortable (one T).



but there are other libraries maybe more audited:

* [Make HTML Table Sortable With sort-table Library | CSS Script](https://www.cssscript.com/html-table-sortable/)
* [Top 7: Best Table Sorter JavaScript and jQuery Plugins | Our Code World](https://ourcodeworld.com/articles/read/619/top-7-best-table-sorter-javascript-and-jquery-plugins)

**Comment by jscher2000** [comment]
The code for the page is open source and runs locally, so you can download the zip file of this repository and experiment with adding sorting to the table.

The default sort order is: enabled extensions, disabled extensions, enabled themes disabled themes, and then by name within each category. If you do not care to preserve that option, your implementation will be simpler than if you do.

**Comment by brisdaz** [comment]
>  you could always donate to Mozilla. https://donate.mozilla.org/

DONE. Sorry for the delay and thanks!

![image](https://user-images.githubusercontent.com/50305553/82474803-f0cc7500-9b0e-11ea-8623-127b9b667339.png)
