### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by g1thub11** [jscher2000/Firefox-File-Utilities#2]
Hello.

I have a large .json session file, that won't load on https://www.jeffersonscher.com/ffu/scrounger.html. How do I use the Session History Scrounger files on GitHub to recover the session?

**Comment by jscher2000** [comment]
You can use a script in the Browser Console to do the decompression (the step that fills the textarea with JSON). Not sure the Scrounger will be able to handle the decompressed script, either:

https://gist.github.com/jscher2000/4403507e33df0918289619edb83f8193

**Comment by g1thub11** [comment]
I have tried using the decompreesed .jsonlz4, but that didn't work either. Is there a way to try recover the session by a script in the Browser Console?
